---
abstract: 'Perl interface to issm.tk'
author:
  - 'Alexandria Marie Wolcott <alyx@woomoo.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.102400'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Shorten-ISSM
requires:
  Carp: 0
  Exporter: 0
  LWP::Simple: 0
  WWW::Shorten::generic: 0
  perl: 5.006
version: 0.002
